# This playbook will install oracle Java8
# will setup JAVA_HOME after installation
---
- name: Java Installation
  hosts: webservers
  environment:
    JAVA_HOME: JAVA_HOME="/usr/lib/jvm/java-8-oracle"
  tasks:
    - name: Install add-apt-repostory
      become: yes
      apt: name=software-properties-common state=latest
    - name: Add Oracle Java Repository
      become: yes
      apt_repository: repo='ppa:webupd8team/java'
    - name: Accept Java 8 License
      become: yes
      debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
    - name: Install Oracle Java 8
      become: yes
      apt: name={{item}} state=latest
      with_items:
        - oracle-java8-installer
        - ca-certificates
        - oracle-java8-set-default